import { vars } from "nativewind";

export const colorPalettes = {
  light:{
    "--color-input-background": "#FFFFFF",
    "--color-input-border": "#E1E1E1",
    "--color-input-placeholder": "#A3A3A8",
    "--color-input-text": "#000000",
    "--color-input-icon": "#DDDDE4",
    "--color-background": "#FFFFFF",
    "--color-brainBox": "#757474",
    "--color-content-background": "#F7F7F8",
    "--color-content-text": "#494949",
    "--color-font-title": "#FFFFFF",
    "--color-font-subtitle": "#FFFFFF",
    "--color-font-text": "#FFFFFF",
    "--color-primary": "#FFFFFF",
    "--color-border": "#FFFFFF",
    "--color-primary-light": "#5bd1e7",
    "--color-secondary": "#9b6cca",
    "--color-secondary-light": "#dfbeff",
    "--color-tertiary": "#ff88bd",
    "--color-tertiary-light": "#ffc2e6",
    "--color-accent": "#f9c04a",
    "--color-accent-light": "#ffeea9",
    "--color-grey": "#979797",
    "--color-slate": "#38383a",
    "--color-dark": "#1f355b",
    "--color-light": "#FCFDFD",
    "--color-overlay": "rgba(0, 0, 0, .05)",
  },
  dark: {
    "--color-input-background": "#232627",
    "--color-input-border": "#676767",
    "--color-input-placeholder": "#A3A3A8",
    "--color-input-text": "#FFFFFF",
    "--color-input-icon": "#DDDDE4",
    "--color-background": "#141718",
    "--color-brainBox": "#757474",
    "--color-content-background": "#232627",
    "--color-content-text": "#A0A0A5",
    "--color-primary": "#000000",
    "--color-border": "#000000",
    "--color-primary-light": "#5bd1e7",
    "--color-secondary": "#9b6cca",
    "--color-secondary-light": "#dfbeff",
    "--color-tertiary": "#ff88bd",
    "--color-tertiary-light": "#ffc2e6",
    "--color-accent": "#f9c04a",
    "--color-accent-light": "#ffeea9",
    "--color-grey": "#979797",
    "--color-slate": "#38383a",
    "--color-dark": "#1f355b",
    "--color-light": "#1E1E1E",
    "--color-overlay": "rgba(255, 255, 255, .05)"
  },
}

export const themes = {
  light: vars(colorPalettes.light),
  dark: vars(colorPalettes.dark),
};